[
  { name: "naraa", age: "35" },
  { name: "saraa", age: "42" },
  { name: "bold", age: "19" },
  { name: "bat", age: "20" },
  { name: "sukhee", age: "31" },
  { name: "tsetsgee", age: "35" },
  { name: "gerlee", age: "35" },
  { name: "bumaa", age: "35" },
  { name: "oyun", age: "35" },
  { name: "khulan", age: "35" },
  { name: "dashmaa", age: "35" },
  { name: "purev", age: "35" },
  { name: "galaa", age: "35" },
  { name: "khuraa", age: "35" },
  { name: "chamin", age: "35" },
  { name: "jagaa", age: "35" },
  { name: "bataa", age: "35" },
  { name: "boloroo", age: "35" },
  { name: "ankhaa", age: "35" },
  { name: "ganaa", age: "35" },
];
